export const PERMISSIONS = {
  MANAGE_PLATFORM: 'MANAGE_PLATFORM',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PROPERTIES: 'MANAGE_PROPERTIES',
  MANAGE_OWN_PROPERTIES: 'MANAGE_OWN_PROPERTIES',
  MANAGE_OWN_SELLERS: 'MANAGE_OWN_SELLERS',
  MANAGE_OWN_LEADS: 'MANAGE_OWN_LEADS',
  MANAGE_OWN_APPOINTMENTS: 'MANAGE_OWN_APPOINTMENTS',
  VIEW_OWN_PROPERTIES: 'VIEW_OWN_PROPERTIES',
  CREATE_INQUIRY: 'CREATE_INQUIRY',
  MANAGE_OWN_FAVORITES: 'MANAGE_OWN_FAVORITES',
  MANAGE_OWN_PROFILE: 'MANAGE_OWN_PROFILE',
  COMMUNICATE_WITH_ASSIGNED_AGENT: 'COMMUNICATE_WITH_ASSIGNED_AGENT',
  READ_PROPERTIES: 'READ_PROPERTIES',
};

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.MANAGE_PLATFORM,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROPERTIES,
    PERMISSIONS.READ_PROPERTIES,
  ],
  AGENT: [
    PERMISSIONS.MANAGE_OWN_PROPERTIES,
    PERMISSIONS.MANAGE_OWN_SELLERS,
    PERMISSIONS.MANAGE_OWN_LEADS,
    PERMISSIONS.MANAGE_OWN_APPOINTMENTS,
    PERMISSIONS.READ_PROPERTIES,
  ],
  SELLER: [
    PERMISSIONS.MANAGE_OWN_PROFILE,
    PERMISSIONS.VIEW_OWN_PROPERTIES,
    PERMISSIONS.COMMUNICATE_WITH_ASSIGNED_AGENT,
    PERMISSIONS.READ_PROPERTIES,
  ],
  CUSTOMER: [
    PERMISSIONS.READ_PROPERTIES,
    PERMISSIONS.CREATE_INQUIRY,
    PERMISSIONS.MANAGE_OWN_FAVORITES,
  ],
};
