export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
  SELLER: 'SELLER',
  CUSTOMER: 'CUSTOMER',
};

export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: [ROLES.ADMIN, ROLES.AGENT, ROLES.SELLER, ROLES.CUSTOMER],
  [ROLES.ADMIN]: [ROLES.AGENT, ROLES.SELLER, ROLES.CUSTOMER],
  [ROLES.AGENT]: [ROLES.SELLER, ROLES.CUSTOMER],
  [ROLES.SELLER]: [ROLES.CUSTOMER],
  [ROLES.CUSTOMER]: [],
};
